config/routes.rb
Rails.application.routes.draw do

	

  devise_for :admins
	resources :devise
  	devise_for :users, path_name: {sign_in: "login", sign_out: "logout" } 
	root 'books#index'


	resources :autors

	
	resources :books do
		collection do
    		get 'index_admin'
    		post :import
  		end
	end
	
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/autor.rb
class Autor < ApplicationRecord
	has_many :books

	def name_with_initial
    "#{last_name} #{name}"
  end
end

app/models/book.rb
class Book < ApplicationRecord


	belongs_to :autor

	validates :name, :autor_id, :genre, :descriptions, :treasure, presence: true

  scope :books_available, ->{where(available: true)}


def self.search(term)
  if term
    where('name || descriptions || genre || treasure LIKE ?', "%#{term}%").order('id DESC').books_available
  else
    order('id DESC').books_available
  end
end


def self.import(file)
  spreadsheet = Roo::Spreadsheet.open(file.path)
  header = spreadsheet.row(1)
  (2..spreadsheet.last_row).each do |i|
    row = Hash[[header, spreadsheet.row(i)].transpose]
    book = find_by(id: row["id"]) || new
    book.attributes = row.to_hash
    book.save!
  end
end  

def self.open_spreadsheet(file)
  case File.extname(file.original_filename)
  when ".csv" then Roo::CSV.new(file.path, nil, :ignore)
  when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
  when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
  else raise "Unknown file type: #{file.original_filename}"
  end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger

 
end

app/controllers/autors_controller.rb
class AutorsController < ApplicationController

	before_action :set_autor, only: [:show, :edit, :update, :destroy]

  	before_action :authenticate_admin!, :except => [:index, :show]



	def index
		@autors = Autor.all
	end

	def show

	end

	def new
		@autor = Autor.new
	end

	def create
		@autor = Autor.new(autor_params)
		if @autor.save
			redirect_to @autor, success: 'Autor create'
		else
			render :new, danger: 'Autor Autor create'
		end
	end

	def edit

	end

	def update
		if @autor.update_attributes(autor_params)
			redirect_to @autor, success: 'Autor update'
		else
			render :edit, danger: 'Autor don`t update'
		end
	end

	def destroy
		@autor.destroy
		redirect_to autors_path, success: 'Autor delet'
	end

	

	private

	def set_autor
		@autor = Autor.find(params[:id])
	end

	def autor_params
		params.require(:autor).permit(:last_name, :name, :year_of_birth, :year_of_death)
	end

	def authenticate_admin!
		if user_signed_in?
	    	# check if current user is admin
	    	unless current_user.admin
	      	# if current_user is not admin redirect to some route
	      	redirect_to books_url
	    	end
	    	# if current_user is admin he will proceed to edit action
	    else
	    	redirect_to books_url
	    end
  	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

	before_action :set_book, only: [:show, :edit, :update, :destroy]

  	before_action :authenticate_admin!, :except => [:index, :show]



	def index
		#@books = Book.search(params[:search])
		@books = Book.search(params[:term])


		if user_signed_in? && current_user.admin
				redirect_to index_admin_books_url
		end
	end

	def import
	  Book.import(params[:file])

	  redirect_to root_url, notice: 'Book imported.'
	end

	def index_admin
		@books = Book.all
	end

	def show

	end

	def new
		@book = Book.new
	end

	def create
		@book = Book.new(book_params)
		if @book.save
			redirect_to @book, success: 'Book create'
		else
			render :new, danger: 'Book don`t create'
		end
	end

	def edit

	end

	def update
		if @book.update_attributes(book_params)
			redirect_to @book, success: 'Book update'
		else
			render :edit, danger: 'Book don`t update'
		end
	end

	def destroy
		@book.destroy
		redirect_to books_path, success: 'Book delete'
	end



	private

	def set_book
		@book = Book.find(params[:id])
	end

	def book_params
		params.require(:book).permit(:name, :autor_id, :genre, :descriptions, :treasure, :available)
	end

	def authenticate_admin!
		if user_signed_in?
	    	# check if current user is admin
	    	unless current_user.admin
	      	# if current_user is not admin redirect to some route
	      	redirect_to books_url
	    	end
	    	# if current_user is admin he will proceed to edit action
	    else
	    	redirect_to books_url
	    end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/autors/_autor.html.erb
<article class="book">
	<section class="book-head">
		<h2><%= autor.last_name+ " " + autor.name %></h2>
		<%= link_to 'Edit', edit_autor_path(autor) %>
		|
		<%= link_to 'Delete', autor_path(autor), method: :delete, data: { confirm: 'Do you want delete this autor?'} %>
	</section>

	<section class="book-author">
		<h5>Year of birth:</h5>
		<%= autor.year_of_birth %>
		<% if autor.year_of_death? %>
		<h5>Year of death: </h5>
		<%= autor.year_of_death %>
		<% end %>
	</section>
	
</article>

app/views/autors/_form.html.erb
<% if @autor.errors.any? %>
	<div class="alert a;ert-danger">
		<h5><%= t('common.errors') %></h5>
		<ul>
			<%= @autor.errors.full_messages.each do |message| %>
			<li>
				<%= message %>
			</li>
			<% end %>
		</ul>
	</div>
<% end %>


<%= form_for @autor do |f| %>
	<div class="form-group">
		<%= f.label :last_name %>
		<%= f.text_field :last_name, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control'  %>
	</div>

	<div class="form-group">
		<%= f.label :year_of_birth %>
		<%= f.text_field :year_of_birth, class: 'form-control'  %>
	</div>

	<div class="form-group">
		<%= f.label :year_of_death %>
		<%= f.text_field :year_of_death, class: 'form-control'  %>
	</div>

	<div class="form-group">
		<%= f.submit 'Save', class: 'btn btn-primary' %>
		<%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
	</div>
<% end %>

app/views/autors/edit.html.erb
<h1>Edit Autor</h1>


<%= render 'form' %>

app/views/autors/index.html.erb
<h1>Autors</h1>

<%= render @autors %>

app/views/autors/new.html.erb
<h1>New Author</h1>


	<%= render 'form' %>

app/views/autors/show.html.erb
<article class="book">
	<section class="book-head">
		<h1><%= @autor.name %></h1>
		
			<%= link_to 'Edit', edit_autor_path(@autor) %> |
			<%= link_to 'Delete', autor_path(@autor), method: :delete, data: { confirm: 'Do you want delete this autor?'} %>
		
	</section>

	<section class="book-body">
		<%= @autor.year_of_birth %>
	</section>
	
</article>

app/views/books/_book.html.erb
<article class="book">
	<section class="book-head">
		<h2><%= link_to book.name, book_path(book) %></h2>
		<%= link_to 'Edit', edit_book_path(book) %>
		|
		<%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Do you want delete this book?'} %>
	</section>

	<section class="book-author">
		<%= book.autor.last_name+" "+book.autor.name %>
	</section>
	
</article>

app/views/books/_bookadmin.html.erb
<% @books.each do |book| %>
<article class="book">
	<section class="book-head">
		<h2><%= link_to book.name, book_path(book) %></h2>
		<%= link_to 'Edit', edit_book_path(book) %>
		|
		<%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: 'Do you want delete this book?'} %>
	</section>

	<section class="book-author">
		<%= book.autor.last_name+" "+book.autor.name %>
	</section>
	
</article>

<% end %>

app/views/books/_form.html.erb
<% if @book.errors.any? %>
	<div class="alert a;ert-danger">
		<h5><%= t('common.errors') %></h5>
		<ul>
			<%= @book.errors.full_messages.each do |message| %>
			<li>
				<%= message %>
			</li>
			<% end %>
		</ul>
	</div>
<% end %>


<%= form_for @book do |f| %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :autor_id %>
		
		<%= f.collection_select( :autor_id, Autor.all, :id, :name_with_initial, prompt: true) %>
	</div>

	<div class="form-group">
		<%= f.label :genre %>
		<%= f.text_field :genre, class: 'form-control'  %>
	</div>

	<div class="form-group">
		<%= f.label :descriptions %>
		<div class="selectContainer">
			<%= f.text_field :descriptions, class: 'form-control'  %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :treasure %>
		<%= f.text_field :treasure, class: 'form-control'  %>
	</div>

	<div class="form-group">
		<%= f.label :available %>
		<%= f.check_box :available, class: 'form-control'  %>
	</div>

	<div class="form-group">
		<%= f.submit 'Save', class: 'btn btn-primary' %>
		<%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
	</div>
<% end %>

app/views/books/edit.html.erb
<h1>Edit book</h1>

<%= render 'form' %>

app/views/books/index.html.erb
<h1>Books</h1>


<%= form_tag(books_path, method: :get) do %>
	<div class="form-group">
  		<%= text_field_tag :term, params[:term], class: 'form-control'  %>
 	</div>
  	<div class="form-group">
  		<%= submit_tag 'Search', :name => nil , class: 'btn btn-primary' %>
  	</div>
<% end %>


<%= render @books %>

app/views/books/index_admin.html.erb
<h1>List books</h1>

<%= render 'bookadmin' %>

app/views/books/new.html.erb
<h1>New Book</h1>

<h2>Import Products</h2>

<h2>Import</h2>
<%= form_tag import_books_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

<%= render 'form' %>

app/views/books/show.html.erb
<article class="book">
	<section class="book-head">
		<h1><%= @book.name %></h1>
	</section>

	<section class="book-body">
		<h5>Genre:</h3>
		<%= @book.genre %>
	</section>
	<section class="book-body">
		<h5>Descriptions:</h3>
		<%= @book.descriptions %>
	</section>
	<section class="book-body">
		<h5>Treasure:</h3>
		<%= @book.treasure%>
	</section>
	<section class="book-body">
		<h5>Author:</h3>
		<%= @book.autor.last_name+" "+@book.autor.name %>
	</section>
	
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bib</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    

<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <div class="container">
      <a class="navbar-brand" href="<%= books_path %>">All Books</a>
      
      <a class="nav-item nav-link disabled" href="<%= autors_path %>">All autor</a>
      <% if current_user %>
        <% if current_user.admin==true %>
          <a class="nav-item nav-link disabled" href="<%= new_autor_path %>">New autor</a>
          <a class="nav-item nav-link disabled" href="<%= new_book_path %>">New book</a>
        <% end %>
      <% end %>
  </div>
  <div id="container">
    <div id="user_nav">
      <% if user_signed_in? %>
        <%= link_to 'Edit profile', edit_user_registration_path %>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Sign in", new_user_registration_path %>
        <%= link_to "Login", new_user_session_path%>
      <% end %>
    </div>
  </div>>
</nav>
    
    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert alert-success">
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>


  </body>
</html>